<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="6.35.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.35.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Server.Common\Server.Common.csproj" />
    <ProjectReference Include="..\Server.Data\Server.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\Input\Run\" />
  </ItemGroup>

</Project>
